DROP TABLE IF EXISTS `column`;
CREATE TABLE `column` (
  `column_id` int(11) NOT NULL auto_increment,
  `column_query` text,
  `column_style` text,
  `column_header` varchar(255) default NULL,
  `column_exec` varchar(255) default NULL,
  `column_date_format` varchar(255) default NULL,
  `column_number_format` int(11) default NULL,
  `column_order` int(11) default NULL,
  PRIMARY KEY  (`column_id`)
);
INSERT INTO `column` VALUES (1, 'position.position_name', NULL, 'Pos', NULL, NULL, NULL, 10);
INSERT INTO `column` VALUES (2, 'player.player_school', NULL, 'School', NULL, NULL, NULL, 20);
INSERT INTO `column` VALUES (3, 'player.player_height', NULL, 'Height', 'height_convert', NULL, NULL, 30);
INSERT INTO `column` VALUES (4, 'player.player_weight', NULL, 'Weight', NULL, NULL, NULL, 40);
INSERT INTO `column` VALUES (5, 'player.player_vol', NULL, 'Volatility', NULL, NULL, NULL, 50);
INSERT INTO `column` VALUES (6, 'player.player_solec', 'if (player.player_solec <= combine_ratings.combine_low_sole,\r\n"color: #0b0; font-weight: bold",\r\n\r\nif (player.player_solec >= combine_ratings.combine_high_sole,\r\n"color: #00f; font-weight: bold", NULL)\r\n\r\n)', 'Solecismic', NULL, NULL, NULL, 60);
INSERT INTO `column` VALUES (7, 'player.player_40', 'if (player.player_40 >= combine_ratings.combine_low_40,\r\n"color: #0b0; font-weight: bold",\r\n\r\nif (player.player_40 <= combine_ratings.combine_high_40,\r\n"color: #00f; font-weight: bold", NULL)\r\n\r\n)', '40-time', NULL, NULL, NULL, 70);
INSERT INTO `column` VALUES (8, 'player.player_bench', 'if (player.player_bench <= combine_ratings.combine_low_strength,\r\n"color: #0b0; font-weight: bold",\r\n\r\nif (player.player_bench >= combine_ratings.combine_high_strength,\r\n"color: #00f; font-weight: bold", NULL)\r\n\r\n)', 'Bench Press Reps', NULL, NULL, NULL, 80);
INSERT INTO `column` VALUES (9, 'player.player_agil', 'if (player.player_agil >= combine_ratings.combine_low_agil,\r\n"color: #0b0; font-weight: bold",\r\n\r\nif (player.player_agil <= combine_ratings.combine_high_agil,\r\n"color: #00f; font-weight: bold", NULL)\r\n\r\n)', 'Agility', NULL, NULL, NULL, 90);
INSERT INTO `column` VALUES (10, 'player.player_broad', 'if (player.player_broad <= combine_ratings.combine_low_broad,\r\n"color: #0b0; font-weight: bold",\r\n\r\nif (player.player_broad >= combine_ratings.combine_high_broad,\r\n"color: #00f; font-weight: bold", NULL)\r\n\r\n)', 'Broad Jump', 'height_convert', NULL, NULL, 100);
INSERT INTO `column` VALUES (11, 'player.player_pos_drill', 'if (combine_ratings.combine_high_pos is not null, \r\n\r\nif (player.player_pos_drill <= combine_ratings.combine_low_pos,\r\n"color: #0b0; font-weight: bold",\r\n\r\nif (player.player_pos_drill >= combine_ratings.combine_high_pos,\r\n"color: #00f; font-weight: bold", NULL)\r\n\r\n)\r\n\r\n, \r\n\r\nNULL)', 'Position Drill', NULL, NULL, NULL, 110);
INSERT INTO `column` VALUES (12, 'player.player_developed', NULL, 'Developed', NULL, NULL, NULL, 120);
INSERT INTO `column` VALUES (13, 'player.player_dob', NULL, 'Birthdate', NULL, 'n/j/Y', NULL, 130);
INSERT INTO `column` VALUES (14, 'player.player_hometown', NULL, 'Hometown', NULL, NULL, NULL, 140);
INSERT INTO `column` VALUES (15, 'player.player_agent', NULL, 'Agent', NULL, NULL, NULL, 150);
INSERT INTO `column` VALUES (16, 'player.player_experience', NULL, 'Exp', NULL, NULL, NULL, 160);
INSERT INTO `column` VALUES (17, 'team_player.player_loyalty', NULL, 'Loyalty', NULL, NULL, NULL, 170);
INSERT INTO `column` VALUES (18, 'team_player.player_winner', NULL, 'Winner', NULL, NULL, NULL, 180);
INSERT INTO `column` VALUES (19, 'team_player.player_leader', NULL, 'Leader', NULL, NULL, NULL, 190);
INSERT INTO `column` VALUES (20, 'team_player.player_intelligence', NULL, 'Intelligence', NULL, NULL, NULL, 200);
INSERT INTO `column` VALUES (21, 'team_player.player_personality', NULL, 'Personality', NULL, NULL, NULL, 210);
INSERT INTO `column` VALUES (22, 'team_player.player_popularity', NULL, 'Popularity', NULL, NULL, NULL, 220);
INSERT INTO `column` VALUES (23, 'team_player.player_interviewed', NULL, 'Interviewed', NULL, NULL, NULL, 230);
INSERT INTO `column` VALUES (24, 'team_player.player_impression', NULL, 'Impression', NULL, NULL, NULL, 240);
INSERT INTO `column` VALUES (25, 'team_player.player_current', NULL, 'Current', NULL, NULL, NULL, 250);
INSERT INTO `column` VALUES (26, 'team_player.player_future', NULL, 'Future', NULL, NULL, NULL, 260);
INSERT INTO `column` VALUES (27, 'team_player.player_conflicts', NULL, 'Conflicts', NULL, NULL, NULL, 270);
INSERT INTO `column` VALUES (28, 'team_player.player_affinities', NULL, 'Affinities', NULL, NULL, NULL, 280);
INSERT INTO `column` VALUES (29, 'player.player_score', NULL, 'Grade', NULL, NULL, NULL, 41);
INSERT INTO `column` VALUES (30, 'player.player_adj_score', NULL, 'Adjusted Grade', NULL, NULL, NULL, 42);
DROP TABLE IF EXISTS `position_to_attribute`;
CREATE TABLE `position_to_attribute` (
  `position_id` int(11) NOT NULL default '0',
  `attribute_id` int(11) NOT NULL default '0',
  `position_to_attribute_order` int(11) default NULL,
  PRIMARY KEY  (`position_id`,`attribute_id`)
);
INSERT INTO `position_to_attribute` VALUES (1, 1, 1);
INSERT INTO `position_to_attribute` VALUES (1, 2, 2);
INSERT INTO `position_to_attribute` VALUES (1, 3, 3);
INSERT INTO `position_to_attribute` VALUES (1, 4, 4);
INSERT INTO `position_to_attribute` VALUES (1, 5, 5);
INSERT INTO `position_to_attribute` VALUES (1, 6, 6);
INSERT INTO `position_to_attribute` VALUES (1, 7, 7);
INSERT INTO `position_to_attribute` VALUES (1, 8, 8);
INSERT INTO `position_to_attribute` VALUES (1, 9, 9);
INSERT INTO `position_to_attribute` VALUES (1, 10, 10);
INSERT INTO `position_to_attribute` VALUES (1, 11, 11);
INSERT INTO `position_to_attribute` VALUES (1, 12, 12);
INSERT INTO `position_to_attribute` VALUES (1, 13, 13);
INSERT INTO `position_to_attribute` VALUES (1, 14, 14);
INSERT INTO `position_to_attribute` VALUES (2, 15, 1);
INSERT INTO `position_to_attribute` VALUES (2, 16, 2);
INSERT INTO `position_to_attribute` VALUES (2, 17, 3);
INSERT INTO `position_to_attribute` VALUES (2, 18, 4);
INSERT INTO `position_to_attribute` VALUES (2, 19, 5);
INSERT INTO `position_to_attribute` VALUES (2, 20, 6);
INSERT INTO `position_to_attribute` VALUES (2, 21, 7);
INSERT INTO `position_to_attribute` VALUES (2, 22, 8);
INSERT INTO `position_to_attribute` VALUES (2, 23, 9);
INSERT INTO `position_to_attribute` VALUES (2, 24, 10);
INSERT INTO `position_to_attribute` VALUES (2, 25, 11);
INSERT INTO `position_to_attribute` VALUES (2, 26, 12);
INSERT INTO `position_to_attribute` VALUES (2, 27, 13);
INSERT INTO `position_to_attribute` VALUES (2, 28, 14);
INSERT INTO `position_to_attribute` VALUES (2, 29, 15);
INSERT INTO `position_to_attribute` VALUES (3, 30, 1);
INSERT INTO `position_to_attribute` VALUES (3, 31, 2);
INSERT INTO `position_to_attribute` VALUES (3, 32, 3);
INSERT INTO `position_to_attribute` VALUES (3, 16, 4);
INSERT INTO `position_to_attribute` VALUES (3, 17, 5);
INSERT INTO `position_to_attribute` VALUES (3, 18, 6);
INSERT INTO `position_to_attribute` VALUES (3, 21, 7);
INSERT INTO `position_to_attribute` VALUES (3, 22, 8);
INSERT INTO `position_to_attribute` VALUES (3, 24, 9);
INSERT INTO `position_to_attribute` VALUES (3, 25, 10);
INSERT INTO `position_to_attribute` VALUES (3, 28, 11);
INSERT INTO `position_to_attribute` VALUES (3, 29, 12);
INSERT INTO `position_to_attribute` VALUES (4, 30, 1);
INSERT INTO `position_to_attribute` VALUES (4, 31, 2);
INSERT INTO `position_to_attribute` VALUES (4, 32, 3);
INSERT INTO `position_to_attribute` VALUES (4, 22, 4);
INSERT INTO `position_to_attribute` VALUES (4, 23, 5);
INSERT INTO `position_to_attribute` VALUES (4, 24, 6);
INSERT INTO `position_to_attribute` VALUES (4, 25, 7);
INSERT INTO `position_to_attribute` VALUES (4, 33, 8);
INSERT INTO `position_to_attribute` VALUES (4, 34, 9);
INSERT INTO `position_to_attribute` VALUES (4, 35, 10);
INSERT INTO `position_to_attribute` VALUES (4, 36, 13);
INSERT INTO `position_to_attribute` VALUES (5, 22, 1);
INSERT INTO `position_to_attribute` VALUES (5, 23, 2);
INSERT INTO `position_to_attribute` VALUES (5, 24, 3);
INSERT INTO `position_to_attribute` VALUES (5, 25, 4);
INSERT INTO `position_to_attribute` VALUES (5, 33, 5);
INSERT INTO `position_to_attribute` VALUES (5, 34, 6);
INSERT INTO `position_to_attribute` VALUES (5, 35, 7);
INSERT INTO `position_to_attribute` VALUES (5, 26, 8);
INSERT INTO `position_to_attribute` VALUES (5, 27, 9);
INSERT INTO `position_to_attribute` VALUES (5, 28, 10);
INSERT INTO `position_to_attribute` VALUES (5, 29, 11);
INSERT INTO `position_to_attribute` VALUES (6, 30, 1);
INSERT INTO `position_to_attribute` VALUES (6, 31, 2);
INSERT INTO `position_to_attribute` VALUES (6, 32, 3);
INSERT INTO `position_to_attribute` VALUES (6, 28, 4);
INSERT INTO `position_to_attribute` VALUES (6, 36, 5);
INSERT INTO `position_to_attribute` VALUES (7, 30, 1);
INSERT INTO `position_to_attribute` VALUES (7, 31, 2);
INSERT INTO `position_to_attribute` VALUES (7, 32, 3);
INSERT INTO `position_to_attribute` VALUES (7, 28, 4);
INSERT INTO `position_to_attribute` VALUES (8, 30, 1);
INSERT INTO `position_to_attribute` VALUES (8, 31, 2);
INSERT INTO `position_to_attribute` VALUES (8, 32, 3);
INSERT INTO `position_to_attribute` VALUES (8, 28, 4);
INSERT INTO `position_to_attribute` VALUES (9, 37, 1);
INSERT INTO `position_to_attribute` VALUES (9, 38, 2);
INSERT INTO `position_to_attribute` VALUES (9, 39, 3);
INSERT INTO `position_to_attribute` VALUES (9, 14, 4);
INSERT INTO `position_to_attribute` VALUES (10, 40, 1);
INSERT INTO `position_to_attribute` VALUES (10, 41, 2);
INSERT INTO `position_to_attribute` VALUES (10, 42, 3);
INSERT INTO `position_to_attribute` VALUES (10, 43, 4);
INSERT INTO `position_to_attribute` VALUES (11, 44, 1);
INSERT INTO `position_to_attribute` VALUES (11, 45, 2);
INSERT INTO `position_to_attribute` VALUES (11, 46, 3);
INSERT INTO `position_to_attribute` VALUES (11, 50, 4);
INSERT INTO `position_to_attribute` VALUES (11, 51, 5);
INSERT INTO `position_to_attribute` VALUES (11, 28, 6);
INSERT INTO `position_to_attribute` VALUES (12, 44, 1);
INSERT INTO `position_to_attribute` VALUES (12, 45, 2);
INSERT INTO `position_to_attribute` VALUES (12, 46, 3);
INSERT INTO `position_to_attribute` VALUES (12, 50, 4);
INSERT INTO `position_to_attribute` VALUES (12, 51, 5);
INSERT INTO `position_to_attribute` VALUES (12, 28, 6);
INSERT INTO `position_to_attribute` VALUES (13, 44, 1);
INSERT INTO `position_to_attribute` VALUES (13, 45, 2);
INSERT INTO `position_to_attribute` VALUES (13, 47, 3);
INSERT INTO `position_to_attribute` VALUES (13, 48, 4);
INSERT INTO `position_to_attribute` VALUES (13, 49, 5);
INSERT INTO `position_to_attribute` VALUES (13, 46, 6);
INSERT INTO `position_to_attribute` VALUES (13, 50, 7);
INSERT INTO `position_to_attribute` VALUES (13, 51, 8);
INSERT INTO `position_to_attribute` VALUES (13, 28, 9);
INSERT INTO `position_to_attribute` VALUES (13, 29, 10);
INSERT INTO `position_to_attribute` VALUES (14, 44, 1);
INSERT INTO `position_to_attribute` VALUES (14, 45, 2);
INSERT INTO `position_to_attribute` VALUES (14, 47, 3);
INSERT INTO `position_to_attribute` VALUES (14, 48, 4);
INSERT INTO `position_to_attribute` VALUES (14, 49, 5);
INSERT INTO `position_to_attribute` VALUES (14, 46, 6);
INSERT INTO `position_to_attribute` VALUES (14, 50, 7);
INSERT INTO `position_to_attribute` VALUES (14, 51, 8);
INSERT INTO `position_to_attribute` VALUES (14, 28, 9);
INSERT INTO `position_to_attribute` VALUES (14, 29, 10);
INSERT INTO `position_to_attribute` VALUES (15, 44, 1);
INSERT INTO `position_to_attribute` VALUES (15, 47, 2);
INSERT INTO `position_to_attribute` VALUES (15, 48, 3);
INSERT INTO `position_to_attribute` VALUES (15, 49, 4);
INSERT INTO `position_to_attribute` VALUES (15, 50, 5);
INSERT INTO `position_to_attribute` VALUES (15, 51, 6);
INSERT INTO `position_to_attribute` VALUES (15, 52, 7);
INSERT INTO `position_to_attribute` VALUES (15, 26, 8);
INSERT INTO `position_to_attribute` VALUES (15, 27, 9);
INSERT INTO `position_to_attribute` VALUES (15, 28, 10);
INSERT INTO `position_to_attribute` VALUES (15, 29, 11);
INSERT INTO `position_to_attribute` VALUES (16, 44, 1);
INSERT INTO `position_to_attribute` VALUES (16, 47, 2);
INSERT INTO `position_to_attribute` VALUES (16, 48, 3);
INSERT INTO `position_to_attribute` VALUES (16, 49, 4);
INSERT INTO `position_to_attribute` VALUES (16, 50, 5);
INSERT INTO `position_to_attribute` VALUES (16, 51, 6);
INSERT INTO `position_to_attribute` VALUES (16, 52, 7);
INSERT INTO `position_to_attribute` VALUES (16, 26, 8);
INSERT INTO `position_to_attribute` VALUES (16, 27, 9);
INSERT INTO `position_to_attribute` VALUES (16, 28, 10);
INSERT INTO `position_to_attribute` VALUES (16, 29, 11);
INSERT INTO `position_to_attribute` VALUES (4, 28, 11);
INSERT INTO `position_to_attribute` VALUES (4, 29, 12);
ALTER TABLE `team` ADD `team_autopick_wait` INT NULL DEFAULT '0' AFTER `team_autopick`;